import {
	ColumnId,
	FilterOption,
} from 'components/StockScreener/screener.types';

export interface FilterProps {
	name: string;
	columnId: ColumnId;
	category: string[];
	options: FilterOption[];
	filterType: 'numeric' | 'stringmatch';
}

export const FiltersMap: FilterProps[] = [
	{
		name: 'Market Cap',
		columnId: 'm',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Mega-Cap: 200B+', value: 'over-200B' },
			{ name: 'Large-Cap: 10-200B', value: 'between-10B-200B' },
			{ name: 'Mid-Cap: 10-20B', value: 'between-2B-10B' },
			{ name: 'Small-Cap: 300M-20B', value: 'between-300M-2B' },
			{ name: 'Micro-Cap: Under 300M', value: 'under-300M' },
		],
	},
	{
		name: 'PE Ratio',
		columnId: 'pe',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 50', value: 'over-50' },
			{ name: 'From 30-50', value: 'between-30-50' },
			{ name: 'From 20-30', value: 'between-20-30' },
			{ name: 'From 15-20', value: 'between-15-20' },
			{ name: 'From 10-15', value: 'between-10-15' },
			{ name: 'Under 10', value: 'under-10' },
			{ name: 'Under 5', value: 'under-5' },
		],
	},
	{
		name: 'Forward PE',
		columnId: 'fpe',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 50', value: 'over-50' },
			{ name: 'From 30-50', value: 'between-30-50' },
			{ name: 'From 20-30', value: 'between-20-30' },
			{ name: 'From 15-20', value: 'between-15-20' },
			{ name: 'From 10-15', value: 'between-10-15' },
			{ name: 'Under 10', value: 'under-10' },
			{ name: 'Under 5', value: 'under-5' },
		],
	},
	{
		name: 'Exchange',
		columnId: 'exchange',
		category: ['Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'NASDAQ', value: 'NASDAQ' },
			{ name: 'NYSE', value: 'NYSE' },
			{ name: 'NYSE AMERICAN', value: 'NYSEAMERICAN' },
		],
	},
	{
		name: 'Dividend Yield',
		columnId: 'dy',
		category: ['Popular', 'Dividends'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Extreme: Over 10%', value: 'over-10' },
			{ name: 'Very High: Over 5%', value: 'over-5' },
			{ name: 'High: 3-5%', value: 'between-3-5' },
			{ name: 'Moderate: 1-3%', value: 'between-1-3' },
			{ name: 'Low: 0-1%', value: 'between-0-1' },
			{ name: 'Not Zero: Over 0%', value: 'over-0' },
		],
	},
	{
		name: 'Sector',
		columnId: 'se',
		category: ['Popular', 'Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Communication Services', value: 'Communication Services' },
			{ name: 'Consumer Discretionary', value: 'Consumer Discretionary' },
			{ name: 'Consumer Staples', value: 'Consumer Staples' },
			{ name: 'Energy', value: 'Energy' },
			{ name: 'Financials', value: 'Financials' },
			{ name: 'Health Care', value: 'Health Care' },
			{ name: 'Industrials', value: 'Industrials' },
			{ name: 'Information Technology', value: 'Information Technology' },
			{ name: 'Materials', value: 'Materials' },
			{ name: 'Real Estate', value: 'Real Estate' },
			{ name: 'Utilities', value: 'Utilities' },
		],
	},
	{
		name: 'Industry',
		columnId: 'i',
		category: ['Popular', 'Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Aerospace & Defense', value: 'Aerospace & Defense' },
			{ name: 'Air Freight & Logistics', value: 'Air Freight & Logistics' },
			{ name: 'Airlines', value: 'Airlines' },
			{ name: 'Auto Components', value: 'Auto Components' },
			{ name: 'Automobiles', value: 'Automobiles' },
			{ name: 'Banks', value: 'Banks' },
			{ name: 'Beverages', value: 'Beverages' },
			{ name: 'Biotechnology', value: 'Biotechnology' },
			{ name: 'Building Products', value: 'Building Products' },
			{ name: 'Capital Markets', value: 'Capital Markets' },
			{ name: 'Chemicals', value: 'Chemicals' },
			{
				name: 'Commercial Services & Supplies',
				value: 'Commercial Services & Supplies',
			},
			{
				name: 'Communications Equipment',
				value: 'Communications Equipment',
			},
			{
				name: 'Construction & Engineering',
				value: 'Construction & Engineering',
			},
			{ name: 'Construction Materials', value: 'Construction Materials' },
			{ name: 'Consumer Finance', value: 'Consumer Finance' },
			{ name: 'Containers & Packaging', value: 'Containers & Packaging' },
			{ name: 'Distributors', value: 'Distributors' },
			{
				name: 'Diversified Consumer Services',
				value: 'Diversified Consumer Services',
			},
			{
				name: 'Diversified Financial Services',
				value: 'Diversified Financial Services',
			},
			{
				name: 'Diversified Telecommunication Services',
				value: 'Diversified Telecommunication Services',
			},
			{ name: 'Electric Utilities', value: 'Electric Utilities' },
			{ name: 'Electrical Equipment', value: 'Electrical Equipment' },
			{
				name: 'Electronic Equipment, Instruments & Components',
				value: 'Electronic Equipment, Instruments & Components',
			},
			{
				name: 'Energy Equipment & Services',
				value: 'Energy Equipment & Services',
			},
			{ name: 'Entertainment', value: 'Entertainment' },
			{
				name: 'Equity Real Estate Investment Trusts (REITs)',
				value: 'Equity Real Estate Investment Trusts (REITs)',
			},
			{
				name: 'Food & Staples Retailing',
				value: 'Food & Staples Retailing',
			},
			{ name: 'Food Products', value: 'Food Products' },
			{ name: 'Gas Utilities', value: 'Gas Utilities' },
			{
				name: 'Health Care Equipment & Supplies',
				value: 'Health Care Equipment & Supplies',
			},
			{
				name: 'Health Care Providers & Services',
				value: 'Health Care Providers & Services',
			},
			{ name: 'Health Care Technology', value: 'Health Care Technology' },
			{
				name: 'Hotels, Restaurants & Leisure',
				value: 'Hotels, Restaurants & Leisure',
			},
			{ name: 'Household Durables', value: 'Household Durables' },
			{ name: 'Household Products', value: 'Household Products' },
			{
				name: 'Independent Power and Renewable Electricity Producers',
				value: 'Independent Power and Renewable Electricity Producers',
			},
			{
				name: 'Industrial Conglomerates',
				value: 'Industrial Conglomerates',
			},
			{ name: 'Insurance', value: 'Insurance' },
			{
				name: 'Interactive Media & Services',
				value: 'Interactive Media & Services',
			},
			{
				name: 'Internet & Direct Marketing Retail',
				value: 'Internet & Direct Marketing Retail',
			},
			{ name: 'IT Services', value: 'IT Services' },
			{ name: 'Leisure Products', value: 'Leisure Products' },
			{
				name: 'Life Sciences Tools & Services',
				value: 'Life Sciences Tools & Services',
			},
			{ name: 'Machinery', value: 'Machinery' },
			{ name: 'Marine', value: 'Marine' },
			{ name: 'Media', value: 'Media' },
			{ name: 'Metals & Mining', value: 'Metals & Mining' },
			{
				name: 'Mortgage Real Estate Investment Trusts (REITs)',
				value: 'Mortgage Real Estate Investment Trusts (REITs)',
			},
			{ name: 'Multi-Utilities', value: 'Multi-Utilities' },
			{ name: 'Multiline Retail', value: 'Multiline Retail' },
			{
				name: 'Oil, Gas & Consumable Fuels',
				value: 'Oil, Gas & Consumable Fuels',
			},
			{ name: 'Paper & Forest Products', value: 'Paper & Forest Products' },
			{ name: 'Personal Products', value: 'Personal Products' },
			{ name: 'Pharmaceuticals', value: 'Pharmaceuticals' },
			{ name: 'Professional Services', value: 'Professional Services' },
			{
				name: 'Real Estate Management & Development',
				value: 'Real Estate Management & Development',
			},
			{ name: 'Road & Rail', value: 'Road & Rail' },
			{
				name: 'Semiconductors & Semiconductor Equipment',
				value: 'Semiconductors & Semiconductor Equipment',
			},
			{ name: 'Software', value: 'Software' },
			{ name: 'Specialty Retail', value: 'Specialty Retail' },
			{
				name: 'Technology Hardware, Storage & Peripherals',
				value: 'Technology Hardware, Storage & Peripherals',
			},
			{
				name: 'Textiles, Apparel & Luxury Goods',
				value: 'Textiles, Apparel & Luxury Goods',
			},
			{
				name: 'Thrifts & Mortgage Finance',
				value: 'Thrifts & Mortgage Finance',
			},
			{ name: 'Tobacco', value: 'Tobacco' },
			{
				name: 'Trading Companies & Distributors',
				value: 'Trading Companies & Distributors',
			},
			{
				name: 'Transportation Infrastructure',
				value: 'Transportation Infrastructure',
			},
			{ name: 'Water Utilities', value: 'Water Utilities' },
			{
				name: 'Wireless Telecommunication Services',
				value: 'Wireless Telecommunication Services',
			},
		],
	},
	{
		name: 'Country',
		columnId: 'country',
		category: ['Company'],
		filterType: 'stringmatch',
		options: [],
	},
	{
		name: 'Stock Price',
		columnId: 'p',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'Price Change',
		columnId: 'c',
		category: ['Popular'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'Volume',
		columnId: 'v',
		category: ['Popular'],
		filterType: 'numeric',
		options: [],
	},

	{
		name: 'Analyst Rating',
		columnId: 'ar',
		category: ['Popular', 'Analysts'],
		filterType: 'stringmatch',
		options: [],
	},
	{
		name: 'Price Target',
		columnId: 'pt',
		category: ['Popular', 'Analysts'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'Revenue',
		columnId: 'revenue',
		category: ['Financials', 'Popular'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'Net Income',
		columnId: 'netIncome',
		category: ['Financials'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'EPS',
		columnId: 'eps',
		category: ['Financials'],
		filterType: 'numeric',
		options: [],
	},
];
