import {
	ColumnId,
	FilterOption,
} from 'components/StockScreener/screener.types';

export interface FilterProps {
	name: string;
	columnId: ColumnId;
	category: string[];
	options: FilterOption[];
	filterType: 'numeric' | 'stringmatch' | 'date' | 'dateYear';
}

export const FiltersMap: FilterProps[] = [
	{
		name: 'Market Cap',
		columnId: 'm',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Mega-Cap: 200B+', value: 'over-200B' },
			{ name: 'Large-Cap: 10-200B', value: 'between-10B-200B' },
			{ name: 'Mid-Cap: 10-20B', value: 'between-2B-10B' },
			{ name: 'Small-Cap: 300M-20B', value: 'between-300M-2B' },
			{ name: 'Micro-Cap: Under 300M', value: 'under-300M' },
		],
	},
	{
		name: 'PE Ratio',
		columnId: 'pe',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 50', value: 'over-50' },
			{ name: 'From 30-50', value: 'between-30-50' },
			{ name: 'From 20-30', value: 'between-20-30' },
			{ name: 'From 15-20', value: 'between-15-20' },
			{ name: 'From 10-15', value: 'between-10-15' },
			{ name: 'Under 10', value: 'under-10' },
			{ name: 'Under 5', value: 'under-5' },
		],
	},
	{
		name: 'Forward PE',
		columnId: 'fpe',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 50', value: 'over-50' },
			{ name: 'From 30-50', value: 'between-30-50' },
			{ name: 'From 20-30', value: 'between-20-30' },
			{ name: 'From 15-20', value: 'between-15-20' },
			{ name: 'From 10-15', value: 'between-10-15' },
			{ name: 'Under 10', value: 'under-10' },
			{ name: 'Under 5', value: 'under-5' },
		],
	},
	{
		name: 'Exchange',
		columnId: 'exchange',
		category: ['Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'NASDAQ', value: 'NASDAQ' },
			{ name: 'NYSE', value: 'NYSE' },
			{ name: 'NYSE AMERICAN', value: 'NYSEAMERICAN' },
		],
	},
	{
		name: 'Dividend Yield',
		columnId: 'dy',
		category: ['Popular', 'Dividends'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Extreme: Over 10%', value: 'over-10' },
			{ name: 'Very High: Over 5%', value: 'over-5' },
			{ name: 'High: 3-5%', value: 'between-3-5' },
			{ name: 'Moderate: 1-3%', value: 'between-1-3' },
			{ name: 'Low: 0-1%', value: 'between-0-1' },
			{ name: 'Not Zero: Over 0%', value: 'over-0' },
		],
	},
	{
		name: 'Sector',
		columnId: 'se',
		category: ['Popular', 'Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Communication Services', value: 'Communication Services' },
			{ name: 'Consumer Discretionary', value: 'Consumer Discretionary' },
			{ name: 'Consumer Staples', value: 'Consumer Staples' },
			{ name: 'Energy', value: 'Energy' },
			{ name: 'Financials', value: 'Financials' },
			{ name: 'Health Care', value: 'Health Care' },
			{ name: 'Industrials', value: 'Industrials' },
			{ name: 'Information Technology', value: 'Information Technology' },
			{ name: 'Materials', value: 'Materials' },
			{ name: 'Real Estate', value: 'Real Estate' },
			{ name: 'Utilities', value: 'Utilities' },
		],
	},
	{
		name: 'Industry',
		columnId: 'i',
		category: ['Popular', 'Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Aerospace & Defense', value: 'Aerospace & Defense' },
			{ name: 'Air Freight & Logistics', value: 'Air Freight & Logistics' },
			{ name: 'Airlines', value: 'Airlines' },
			{ name: 'Auto Components', value: 'Auto Components' },
			{ name: 'Automobiles', value: 'Automobiles' },
			{ name: 'Banks', value: 'Banks' },
			{ name: 'Beverages', value: 'Beverages' },
			{ name: 'Biotechnology', value: 'Biotechnology' },
			{ name: 'Building Products', value: 'Building Products' },
			{ name: 'Capital Markets', value: 'Capital Markets' },
			{ name: 'Chemicals', value: 'Chemicals' },
			{
				name: 'Commercial Services & Supplies',
				value: 'Commercial Services & Supplies',
			},
			{
				name: 'Communications Equipment',
				value: 'Communications Equipment',
			},
			{
				name: 'Construction & Engineering',
				value: 'Construction & Engineering',
			},
			{ name: 'Construction Materials', value: 'Construction Materials' },
			{ name: 'Consumer Finance', value: 'Consumer Finance' },
			{ name: 'Containers & Packaging', value: 'Containers & Packaging' },
			{ name: 'Distributors', value: 'Distributors' },
			{
				name: 'Diversified Consumer Services',
				value: 'Diversified Consumer Services',
			},
			{
				name: 'Diversified Financial Services',
				value: 'Diversified Financial Services',
			},
			{
				name: 'Diversified Telecommunication Services',
				value: 'Diversified Telecommunication Services',
			},
			{ name: 'Electric Utilities', value: 'Electric Utilities' },
			{ name: 'Electrical Equipment', value: 'Electrical Equipment' },
			{
				name: 'Electronic Equipment, Instruments & Components',
				value: 'Electronic Equipment, Instruments & Components',
			},
			{
				name: 'Energy Equipment & Services',
				value: 'Energy Equipment & Services',
			},
			{ name: 'Entertainment', value: 'Entertainment' },
			{
				name: 'Equity Real Estate Investment Trusts (REITs)',
				value: 'Equity Real Estate Investment Trusts (REITs)',
			},
			{
				name: 'Food & Staples Retailing',
				value: 'Food & Staples Retailing',
			},
			{ name: 'Food Products', value: 'Food Products' },
			{ name: 'Gas Utilities', value: 'Gas Utilities' },
			{
				name: 'Health Care Equipment & Supplies',
				value: 'Health Care Equipment & Supplies',
			},
			{
				name: 'Health Care Providers & Services',
				value: 'Health Care Providers & Services',
			},
			{ name: 'Health Care Technology', value: 'Health Care Technology' },
			{
				name: 'Hotels, Restaurants & Leisure',
				value: 'Hotels, Restaurants & Leisure',
			},
			{ name: 'Household Durables', value: 'Household Durables' },
			{ name: 'Household Products', value: 'Household Products' },
			{
				name: 'Independent Power and Renewable Electricity Producers',
				value: 'Independent Power and Renewable Electricity Producers',
			},
			{
				name: 'Industrial Conglomerates',
				value: 'Industrial Conglomerates',
			},
			{ name: 'Insurance', value: 'Insurance' },
			{
				name: 'Interactive Media & Services',
				value: 'Interactive Media & Services',
			},
			{
				name: 'Internet & Direct Marketing Retail',
				value: 'Internet & Direct Marketing Retail',
			},
			{ name: 'IT Services', value: 'IT Services' },
			{ name: 'Leisure Products', value: 'Leisure Products' },
			{
				name: 'Life Sciences Tools & Services',
				value: 'Life Sciences Tools & Services',
			},
			{ name: 'Machinery', value: 'Machinery' },
			{ name: 'Marine', value: 'Marine' },
			{ name: 'Media', value: 'Media' },
			{ name: 'Metals & Mining', value: 'Metals & Mining' },
			{
				name: 'Mortgage Real Estate Investment Trusts (REITs)',
				value: 'Mortgage Real Estate Investment Trusts (REITs)',
			},
			{ name: 'Multi-Utilities', value: 'Multi-Utilities' },
			{ name: 'Multiline Retail', value: 'Multiline Retail' },
			{
				name: 'Oil, Gas & Consumable Fuels',
				value: 'Oil, Gas & Consumable Fuels',
			},
			{ name: 'Paper & Forest Products', value: 'Paper & Forest Products' },
			{ name: 'Personal Products', value: 'Personal Products' },
			{ name: 'Pharmaceuticals', value: 'Pharmaceuticals' },
			{ name: 'Professional Services', value: 'Professional Services' },
			{
				name: 'Real Estate Management & Development',
				value: 'Real Estate Management & Development',
			},
			{ name: 'Road & Rail', value: 'Road & Rail' },
			{
				name: 'Semiconductors & Semiconductor Equipment',
				value: 'Semiconductors & Semiconductor Equipment',
			},
			{ name: 'Software', value: 'Software' },
			{ name: 'Specialty Retail', value: 'Specialty Retail' },
			{
				name: 'Technology Hardware, Storage & Peripherals',
				value: 'Technology Hardware, Storage & Peripherals',
			},
			{
				name: 'Textiles, Apparel & Luxury Goods',
				value: 'Textiles, Apparel & Luxury Goods',
			},
			{
				name: 'Thrifts & Mortgage Finance',
				value: 'Thrifts & Mortgage Finance',
			},
			{ name: 'Tobacco', value: 'Tobacco' },
			{
				name: 'Trading Companies & Distributors',
				value: 'Trading Companies & Distributors',
			},
			{
				name: 'Transportation Infrastructure',
				value: 'Transportation Infrastructure',
			},
			{ name: 'Water Utilities', value: 'Water Utilities' },
			{
				name: 'Wireless Telecommunication Services',
				value: 'Wireless Telecommunication Services',
			},
		],
	},
	{
		name: 'Stock Price',
		columnId: 'p',
		category: ['Popular', 'Valuation'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 1000', value: 'over-1000' },
			{ name: 'From 500-1000', value: 'between-500-1000' },
			{ name: 'From 100-500', value: 'between-100-500' },
			{ name: 'From 50-100', value: 'between-50-100' },
			{ name: 'From 20-50', value: 'between-20-50' },
			{ name: 'From 10-20', value: 'between-10-20' },
			{ name: 'Under 20', value: 'under-20' },
			{ name: 'Under 10', value: 'under-10' },
			{ name: 'Under 5', value: 'under-5' },
			{ name: 'Under 1', value: 'under-1' },
		],
	},
	{
		name: 'Price Change',
		columnId: 'c',
		category: ['Popular'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 100%', value: 'over-100' },
			{ name: 'Over 50%', value: 'over-50' },
			{ name: 'Over 20%', value: 'over-20' },
			{ name: 'Over 10%', value: 'over-10' },
			{ name: 'Over 5%', value: 'over-5' },
			{ name: 'Over 1%', value: 'over-1' },
			{ name: 'From 0-1%', value: 'between-0-1' },
			{ name: 'From -1-0%', value: 'between-X1-0' },
			{ name: 'Under -1%', value: 'under-X1' },
			{ name: 'Under -5%', value: 'under-X5' },
			{ name: 'Under -10%', value: 'under-X10' },
			{ name: 'Under -20%', value: 'under-X20' },
			{ name: 'Under -50%', value: 'under-X50' },
			{ name: 'Under -100%', value: 'under-X100' },
		],
	},
	{
		name: 'Volume',
		columnId: 'v',
		category: ['Popular'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 100M', value: 'over-100M' },
			{ name: 'Over 10M', value: 'over-10M' },
			{ name: 'Over 1M', value: 'over-1M' },
			{ name: 'Over 100K', value: 'over-100K' },
			{ name: 'Over 10K', value: 'over-10K' },
			{ name: 'Over 1K', value: 'over-1K' },
			{ name: 'Over 0', value: 'over-0' },
			{ name: 'Under 1K', value: 'under-1K' },
			{ name: 'Under 10K', value: 'under-10K' },
			{ name: 'Under 100K', value: 'under-100K' },
			{ name: 'Under 1M', value: 'under-1M' },
			{ name: 'Under 10M', value: 'under-10M' },
			{ name: 'Under 100M', value: 'under-100M' },
		],
	},
	{
		name: 'Analyst Rating',
		columnId: 'ar',
		category: ['Popular'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Strong Buy', value: 'Strong Buy' },
			{ name: 'Buy', value: 'Buy' },
			{ name: 'Hold', value: 'Hold' },
			{ name: 'Sell', value: 'Sell' },
			{ name: 'Strong Sell', value: 'Strong Sell' },
		],
	},
	{
		name: 'Analyst Count',
		columnId: 'ac',
		category: ['Popular'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 40', value: 'over-40' },
			{ name: 'Over 30', value: 'over-30' },
			{ name: 'Over 20', value: 'over-20' },
			{ name: 'Over 10', value: 'over-10' },
			{ name: 'Over 5', value: 'over-5' },
			{ name: 'Over 3', value: 'over-3' },
			{ name: 'Over 2', value: 'over-2' },
			{ name: 'Over 1', value: 'over-1' },
			{ name: 'Over 0', value: 'over-0' },
		],
	},
	{
		name: 'Price Target',
		columnId: 'ptc',
		category: ['Popular'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: '100%+ Above', value: 'over-100' },
			{ name: '50%+ Above', value: 'over-50' },
			{ name: '20%+ Above', value: 'over-20' },
			{ name: '10%+ Above', value: 'over-10' },
			{ name: '5%+ Above', value: 'over-5' },
			{ name: 'Above', value: 'over-1' },
			{ name: 'Below', value: 'under-0' },
			{ name: '-5%+ Below', value: 'under-X5' },
			{ name: '-10%+ Below', value: 'under-X10' },
			{ name: '-20%+ Below', value: 'under-X20' },
			{ name: '-50%+ Below', value: 'under-X50' },
			{ name: '-100%+ Below', value: 'under-X100' },
		],
	},
	{
		name: 'Country',
		columnId: 'country',
		category: ['Company'],
		filterType: 'stringmatch',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'United States', value: 'United States' },
			{ name: 'Canada', value: 'Canada' },
			{ name: 'China', value: 'China' },
			{ name: 'United Kingdom', value: 'United Kingdom' },
			{ name: 'Israel', value: 'Israel' },
			{ name: 'Bermuda', value: 'Bermuda' },
			{ name: 'Brazil', value: 'Brazil' },
			{ name: 'Switzerland', value: 'Switzerland' },
			{ name: 'Hong Kong', value: 'Hong Kong' },
			{ name: 'Ireland', value: 'Ireland' },
			{ name: 'Netherlands', value: 'Netherlands' },
			{ name: 'Cayman Islands', value: 'Cayman Islands' },
			{ name: 'Germany', value: 'Germany' },
			{ name: 'Argentina', value: 'Argentina' },
			{ name: 'France', value: 'France' },
			{ name: 'Mexico', value: 'Mexico' },
			{ name: 'Greece', value: 'Greece' },
			{ name: 'Luxembourg', value: 'Luxembourg' },
			{ name: 'Singapore', value: 'Singapore' },
			{ name: 'Chile', value: 'Chile' },
			{ name: 'Japan', value: 'Japan' },
			{ name: 'South Korea', value: 'South Korea' },
			{ name: 'India', value: 'India' },
			{ name: 'Taiwan', value: 'Taiwan' },
			{ name: 'Australia', value: 'Australia' },
			{ name: 'Monaco', value: 'Monaco' },
			{ name: 'Sweden', value: 'Sweden' },
			{ name: 'Denmark', value: 'Denmark' },
			{ name: 'South Africa', value: 'South Africa' },
			{ name: 'Belgium', value: 'Belgium' },
			{ name: 'Spain', value: 'Spain' },
			{ name: 'Peru', value: 'Peru' },
			{ name: 'Colombia', value: 'Colombia' },
			{ name: 'Italy', value: 'Italy' },
			{ name: 'British Virgin Islands', value: 'British Virgin Islands' },
			{ name: 'Russia', value: 'Russia' },
			{ name: 'Norway', value: 'Norway' },
			{ name: 'Puerto Rico', value: 'Puerto Rico' },
			{ name: 'Uruguay', value: 'Uruguay' },
			{ name: 'Cyprus', value: 'Cyprus' },
			{ name: 'Jersey', value: 'Jersey' },
			{ name: 'Turkey', value: 'Turkey' },
			{ name: 'Panama', value: 'Panama' },
			{ name: 'Indonesia', value: 'Indonesia' },
			{ name: 'Philippines', value: 'Philippines' },
			{ name: 'Bahamas', value: 'Bahamas' },
			{ name: 'MINNESOTA', value: 'MINNESOTA' },
			{ name: 'Finland', value: 'Finland' },
			{ name: 'New Zealand', value: 'New Zealand' },
			{ name: 'the Netherlands', value: 'the Netherlands' },
			{ name: 'Malta', value: 'Malta' },
			{ name: 'COLORADO', value: 'COLORADO' },
			{ name: 'Gibraltar', value: 'Gibraltar' },
			{ name: 'Thailand', value: 'Thailand' },
			{ name: 'Austria', value: 'Austria' },
			{ name: 'Costa Rica', value: 'Costa Rica' },
			{ name: 'Guernsey', value: 'Guernsey' },
			{ name: 'Macau', value: 'Macau' },
			{ name: 'England', value: 'England' },
			{ name: 'Korea', value: 'Korea' },
		],
	},
	{
		name: 'Employees',
		columnId: 'employees',
		category: ['Company'],
		filterType: 'numeric',
		options: [
			{ name: 'Any', value: 'Any' },
			{ name: 'Over 500K', value: 'over-500K' },
			{ name: 'Over 300K', value: 'over-300K' },
			{ name: 'Over 200K', value: 'over-200K' },
			{ name: 'Over 100K', value: 'over-100K' },
			{ name: 'Over 10K', value: 'over-10K' },
			{ name: 'Over 1K', value: 'over-1K' },
			{ name: 'Over 100', value: 'over-100' },
			{ name: 'Over 0', value: 'over-0' },
			{ name: 'Under 1K', value: 'under-1K' },
			{ name: 'Under 10K', value: 'under-10K' },
			{ name: 'Under 100K', value: 'under-100K' },
		],
	},
	{
		name: 'Founded',
		columnId: 'founded',
		category: ['Company'],
		filterType: 'dateYear',
		options: [
			{ name: 'Any', value: 'Any', div: true },
			{ name: 'Over 100 Years', value: 'over-100' },
			{ name: 'Over 50 Years', value: 'over-50' },
			{ name: 'Over 20 Years', value: 'over-20' },
			{ name: 'Over 10 Years', value: 'over-10' },
			{ name: 'Over 5 Years', value: 'over-5' },
			{ name: 'Over 3 Years', value: 'over-3', div: true },
			{ name: 'Last Year', value: 'last-year' },
			{ name: 'This Year', value: 'this-year', div: true },
			{ name: 'Within 3 Years', value: 'under-3' },
			{ name: 'Within 5 Years', value: 'under-5' },
			{ name: 'Within 10 Years', value: 'under-10' },
			{ name: 'Within 20 Years', value: 'under-20' },
			{ name: 'Within 50 Years', value: 'under-50' },
			{ name: 'Within 100 Years', value: 'under-100' },
		],
	},
	{
		name: 'IPO Date',
		columnId: 'ipoDate',
		category: ['Company'],
		filterType: 'date',
		options: [
			{ name: 'Any', value: 'Any', div: true },
			{ name: 'Today', value: 'today' },
			{ name: 'Yesterday', value: 'yesterday' },
			{ name: 'Past Week', value: 'under-7D' },
			{ name: 'Past Month', value: 'under-1M' },
			{ name: 'Past 3 Months', value: 'under-3M' },
			{ name: 'Past 6 Months', value: 'under-6M' },
			{ name: 'Past 12 Months', value: 'under-12M', div: true },
			{ name: 'This Year', value: 'this-year' },
			{ name: 'Last Year', value: 'last-year', div: true },
			{ name: 'Within 3 Years', value: 'under-3Y' },
			{ name: 'Within 5 Years', value: 'under-5Y' },
			{ name: 'Within 10 Years', value: 'under-10Y' },
			{ name: 'Within 20 Years', value: 'under-20Y' },
		],
	},
	{
		name: 'Revenue',
		columnId: 'revenue',
		category: ['Financials'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'Net Income',
		columnId: 'netIncome',
		category: ['Financials'],
		filterType: 'numeric',
		options: [],
	},
	{
		name: 'EPS',
		columnId: 'eps',
		category: ['Financials'],
		filterType: 'numeric',
		options: [],
	},
];
